include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    - require_trailing_commas
    - cancel_subscriptions
    - always_declare_return_types
    - close_sinks
    - combinators_ordering
    - comment_references
    - invalid_case_patterns
    - library_annotations
    - one_member_abstracts
    - only_throw_errors
    - prefer_double_quotes
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_final_parameters
    - sort_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_getters_setters
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - use_enums
    - use_named_constants
    - use_to_and_as_if_applicable
    - directives_ordering
    - eol_at_end_of_file

