include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    always_specify_types: true
    always_declare_return_types: true
    avoid_returning_this: true
    always_put_required_named_parameters_first: true
    avoid_redundant_argument_values: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true
    avoid_classes_with_only_static_members: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_catches_without_on_clauses: true
    avoid_multiple_declarations_per_line: true
    avoid_implementing_value_types: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_dynamic_calls: true
    avoid_escaping_inner_quotes: true
    avoid_js_rounded_ints: true
    avoid_void_async: true
    avoid_unused_constructor_parameters: true
    avoid_type_to_string: true
    avoid_slow_async_io: true
    avoid_setters_without_getters: true
    cast_nullable_to_non_nullable: true
    cascade_invocations: true
    cancel_subscriptions: true
    close_sinks: true
    conditional_uri_does_not_exist: true
    combinators_ordering: true
    comment_references: true
    directives_ordering: true
    discarded_futures: true
    eol_at_end_of_file: true
    join_return_with_assignment: true
    invalid_case_patterns: true
    invalid_runtime_check_with_js_interop_types: true
    library_annotations: true
    literal_only_boolean_expressions: true
    lines_longer_than_80_chars: true
    matching_super_parameters: true
    missing_whitespace_between_adjacent_strings: true
    missing_code_block_language_in_doc_comment: true
    no_adjacent_strings_in_list: true
    no_literal_bool_comparisons: true
    no_wildcard_variable_uses: true
    no_self_assignments: true
    no_runtimeType_toString: true
    noop_primitive_operations: true
    one_member_abstracts: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_double_quotes: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_parameters: true
    prefer_foreach: true
    prefer_null_aware_method_calls: true
    prefer_mixin: true
    prefer_void_to_null: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    sort_pub_dependencies: true
    sized_box_shrink_expand: true
    test_types_in_equals: true
    throw_in_finally: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    type_literal_in_constant_pattern: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_library_name: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_enums: true
    use_decorated_box: true
    use_colored_box: true
    use_named_constants: true
    use_string_buffers: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true
    use_if_null_to_convert_nulls_to_bools: true
    unsafe_html: true
    unreachable_from_main: true
    unnecessary_statements: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
