name: cattestapp
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.5.3
  flutter: 3.24.3

dependencies:
  dio: 5.7.0
  equatable: 2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  flutter_localizations:
    sdk: flutter
  fpdart: 1.1.0
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.13
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.7
  json_serializable: 6.8.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
